# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-15 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oauthqquser',
            old_name='create_tiem',
            new_name='create_time',
        ),
    ]
