# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-15 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190114_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='create_tiem',
            new_name='create_time',
        ),
    ]
